const ACHIEVEMENTS = [
  {
    id: 'first-lesson',
    name: { fa: 'اولین قدم', en: 'First Step' },
    description: { fa: 'اولین درس را کامل کن', en: 'Complete your first lesson' },
    icon: '🎯',
    category: 'learning',
    xpReward: 100,
  },
  {
    id: 'streak-7',
    name: { fa: 'استریک ۷ روزه', en: '7-Day Streak' },
    description: { fa: '۷ روز متوالی تمرین کن', en: 'Practice for 7 days straight' },
    icon: '🔥',
    category: 'streak',
    xpReward: 150,
  },
  {
    id: 'streak-30',
    name: { fa: 'استریک ۳۰ روزه', en: '30-Day Streak' },
    description: { fa: '۳۰ روز متوالی تمرین کن', en: 'Practice for 30 days straight' },
    icon: '🔥',
    category: 'streak',
    xpReward: 500,
  },
  {
    id: 'streak-100',
    name: { fa: 'استاد استمرار', en: 'Streak Master' },
    description: { fa: '۱۰۰ روز متوالی تمرین کن', en: 'Practice for 100 days straight' },
    icon: '💪',
    category: 'streak',
    xpReward: 2000,
  },
  {
    id: 'words-50',
    name: { fa: 'واژه‌آموز', en: 'Word Learner' },
    description: { fa: '۵۰ کلمه یاد بگیر', en: 'Learn 50 words' },
    icon: '📝',
    category: 'vocabulary',
    xpReward: 100,
  },
  {
    id: 'words-100',
    name: { fa: 'واژه‌ساز', en: 'Word Builder' },
    description: { fa: '۱۰۰ کلمه یاد بگیر', en: 'Learn 100 words' },
    icon: '📚',
    category: 'vocabulary',
    xpReward: 200,
  },
  {
    id: 'words-500',
    name: { fa: 'گنجینه لغات', en: 'Vocabulary Vault' },
    description: { fa: '۵۰۰ کلمه یاد بگیر', en: 'Learn 500 words' },
    icon: '🏆',
    category: 'vocabulary',
    xpReward: 1000,
  },
  {
    id: 'words-1000',
    name: { fa: 'دایرةالمعارف', en: 'Walking Dictionary' },
    description: { fa: '۱۰۰۰ کلمه یاد بگیر', en: 'Learn 1000 words' },
    icon: '🎓',
    category: 'vocabulary',
    xpReward: 2500,
  },
  {
    id: 'lessons-10',
    name: { fa: 'یادگیرنده', en: 'Learner' },
    description: { fa: '۱۰ درس را کامل کن', en: 'Complete 10 lessons' },
    icon: '📖',
    category: 'learning',
    xpReward: 200,
  },
  {
    id: 'lessons-50',
    name: { fa: 'دانشجو', en: 'Student' },
    description: { fa: '۵۰ درس را کامل کن', en: 'Complete 50 lessons' },
    icon: '🎒',
    category: 'learning',
    xpReward: 500,
  },
  {
    id: 'lessons-100',
    name: { fa: 'محقق', en: 'Scholar' },
    description: { fa: '۱۰۰ درس را کامل کن', en: 'Complete 100 lessons' },
    icon: '🔬',
    category: 'learning',
    xpReward: 1000,
  },
  {
    id: 'perfect-lesson',
    name: { fa: 'بی‌نقص', en: 'Perfect Score' },
    description: { fa: 'یک درس را بدون هیچ خطایی کامل کن', en: 'Complete a lesson with zero mistakes' },
    icon: '⭐',
    category: 'learning',
    xpReward: 150,
  },
  {
    id: 'perfect-week',
    name: { fa: 'هفته طلایی', en: 'Golden Week' },
    description: { fa: 'تمام درس‌های یک هفته را بی‌نقص کامل کن', en: 'Complete all lessons in a week perfectly' },
    icon: '👑',
    category: 'learning',
    xpReward: 500,
  },
  {
    id: 'stories-5',
    name: { fa: 'داستان‌خوان', en: 'Storyteller' },
    description: { fa: '۵ داستان بخوان', en: 'Read 5 stories' },
    icon: '📕',
    category: 'stories',
    xpReward: 200,
  },
  {
    id: 'stories-20',
    name: { fa: 'کتاب‌خوان حرفه‌ای', en: 'Bookworm' },
    description: { fa: '۲۰ داستان بخوان', en: 'Read 20 stories' },
    icon: '📚',
    category: 'stories',
    xpReward: 500,
  },
  {
    id: 'scenarios-5',
    name: { fa: 'سناریوکار', en: 'Scenario Player' },
    description: { fa: '۵ سناریو را کامل کن', en: 'Complete 5 scenarios' },
    icon: '🎭',
    category: 'scenarios',
    xpReward: 200,
  },
  {
    id: 'ai-chat-10',
    name: { fa: 'همصحبت هوش مصنوعی', en: 'AI Conversationalist' },
    description: { fa: '۱۰ مکالمه با معلم هوش مصنوعی داشته باش', en: 'Have 10 conversations with AI tutor' },
    icon: '🤖',
    category: 'ai',
    xpReward: 300,
  },
  {
    id: 'level-5',
    name: { fa: 'سطح ۵', en: 'Level 5' },
    description: { fa: 'به سطح ۵ برس', en: 'Reach level 5' },
    icon: '⬆️',
    category: 'level',
    xpReward: 500,
  },
  {
    id: 'level-10',
    name: { fa: 'سطح ۱۰', en: 'Level 10' },
    description: { fa: 'به سطح ۱۰ برس', en: 'Reach level 10' },
    icon: '🚀',
    category: 'level',
    xpReward: 1000,
  },
  {
    id: 'quiz-master',
    name: { fa: 'استاد آزمون', en: 'Quiz Master' },
    description: { fa: 'در ۱۰ آزمون نمره کامل بگیر', en: 'Score 100% on 10 quizzes' },
    icon: '🏅',
    category: 'quiz',
    xpReward: 500,
  },
];

export const ACHIEVEMENT_CATEGORIES = [
  { id: 'learning', label: { fa: 'یادگیری', en: 'Learning' } },
  { id: 'streak', label: { fa: 'استمرار', en: 'Streak' } },
  { id: 'vocabulary', label: { fa: 'واژگان', en: 'Vocabulary' } },
  { id: 'stories', label: { fa: 'داستان‌ها', en: 'Stories' } },
  { id: 'scenarios', label: { fa: 'سناریوها', en: 'Scenarios' } },
  { id: 'ai', label: { fa: 'هوش مصنوعی', en: 'AI' } },
  { id: 'level', label: { fa: 'سطح', en: 'Level' } },
  { id: 'quiz', label: { fa: 'آزمون', en: 'Quiz' } },
];

export default ACHIEVEMENTS;