const JOURNEYS = [
  {
    id: 'integration',
    icon: '🏠',
    title: { fa: 'مسیر ادغام', en: 'Integration Path' },
    description: {
      fa: 'یادگیری زبان و فرهنگ آلمان برای زندگی روزمره',
      en: 'Learn German language and culture for everyday life',
    },
    color: 'from-green-400 to-emerald-600',
    totalStages: 10,
    stages: [
      { id: 'greetings', title: { fa: 'سلام و احوالپرسی', en: 'Greetings' }, icon: '👋' },
      { id: 'shopping', title: { fa: 'خرید روزانه', en: 'Daily Shopping' }, icon: '🛒' },
      { id: 'transport', title: { fa: 'حمل و نقل', en: 'Transportation' }, icon: '🚌' },
      { id: 'healthcare', title: { fa: 'درمان و دکتر', en: 'Healthcare' }, icon: '🏥' },
      { id: 'communication', title: { fa: 'ارتباطات', en: 'Communication' }, icon: '📱' },
      { id: 'bureaucracy', title: { fa: 'کارهای اداری', en: 'Bureaucracy' }, icon: '📄' },
      { id: 'community', title: { fa: 'دوستان و اجتماع', en: 'Friends & Community' }, icon: '👥' },
      { id: 'culture', title: { fa: 'فرهنگ و رسوم', en: 'Culture & Customs' }, icon: '🎭' },
      { id: 'emergency', title: { fa: 'موقعیت‌های اضطراری', en: 'Emergencies' }, icon: '🆘' },
      { id: 'citizenship', title: { fa: 'شهروندی', en: 'Citizenship' }, icon: '🎉' },
    ],
  },
  {
    id: 'career',
    icon: '💼',
    title: { fa: 'مسیر شغلی', en: 'Career Path' },
    description: {
      fa: 'آمادگی برای کار و مصاحبه در آلمان',
      en: 'Prepare for work and interviews in Germany',
    },
    color: 'from-blue-400 to-indigo-600',
    totalStages: 8,
    stages: [
      { id: 'intro', title: { fa: 'معرفی حرفه‌ای', en: 'Professional Intro' }, icon: '🎯' },
      { id: 'cv', title: { fa: 'رزومه آلمانی', en: 'German CV' }, icon: '📝' },
      { id: 'interview', title: { fa: 'مصاحبه شغلی', en: 'Job Interview' }, icon: '🤝' },
      { id: 'emails', title: { fa: 'ایمیل‌های کاری', en: 'Work Emails' }, icon: '✉️' },
      { id: 'meetings', title: { fa: 'جلسات کاری', en: 'Meetings' }, icon: '📊' },
      { id: 'salary', title: { fa: 'مذاکره حقوق', en: 'Salary Negotiation' }, icon: '💰' },
      { id: 'law', title: { fa: 'قوانین کار', en: 'Labor Law' }, icon: '⚖️' },
      { id: 'growth', title: { fa: 'پیشرفت شغلی', en: 'Career Growth' }, icon: '🚀' },
    ],
  },
  {
    id: 'education',
    icon: '🎓',
    title: { fa: 'مسیر تحصیلی', en: 'Education Path' },
    description: {
      fa: 'آمادگی برای تحصیل در دانشگاه‌های آلمان',
      en: 'Prepare for studying at German universities',
    },
    color: 'from-purple-400 to-violet-600',
    totalStages: 10,
    stages: [
      { id: 'course', title: { fa: 'انتخاب رشته', en: 'Course Selection' }, icon: '🔍' },
      { id: 'documents', title: { fa: 'مدارک مورد نیاز', en: 'Required Documents' }, icon: '📋' },
      { id: 'motivation', title: { fa: 'انگیزه‌نامه', en: 'Motivation Letter' }, icon: '✍️' },
      { id: 'exam', title: { fa: 'آزمون ورودی', en: 'Entrance Exam' }, icon: '📚' },
      { id: 'interview', title: { fa: 'مصاحبه دانشگاه', en: 'University Interview' }, icon: '🎤' },
      { id: 'visa', title: { fa: 'ویزای تحصیلی', en: 'Student Visa' }, icon: '🛂' },
      { id: 'dormitory', title: { fa: 'خوابگاه', en: 'Dormitory' }, icon: '🏘️' },
      { id: 'semester', title: { fa: 'ترم اول', en: 'First Semester' }, icon: '📖' },
      { id: 'job', title: { fa: 'کار دانشجویی', en: 'Student Job' }, icon: '💵' },
      { id: 'graduation', title: { fa: 'فارغ‌التحصیلی', en: 'Graduation' }, icon: '🎓' },
    ],
  },
  {
    id: 'goethe-a1',
    icon: '📝',
    title: { fa: 'آزمون گوته A1', en: 'Goethe A1 Exam' },
    description: {
      fa: 'آمادگی کامل برای آزمون Goethe-Zertifikat A1',
      en: 'Complete preparation for Goethe-Zertifikat A1',
    },
    color: 'from-amber-400 to-orange-600',
    totalStages: 8,
    stages: [
      { id: 'listening', title: { fa: 'بخش شنیداری', en: 'Listening Section' }, icon: '🎧' },
      { id: 'reading', title: { fa: 'بخش خواندن', en: 'Reading Section' }, icon: '📖' },
      { id: 'writing', title: { fa: 'بخش نوشتن', en: 'Writing Section' }, icon: '✍️' },
      { id: 'speaking', title: { fa: 'بخش گفتاری', en: 'Speaking Section' }, icon: '🗣️' },
      { id: 'vocabulary', title: { fa: 'واژگان ضروری', en: 'Essential Vocabulary' }, icon: '📝' },
      { id: 'grammar', title: { fa: 'گرامر پایه', en: 'Basic Grammar' }, icon: '📐' },
      { id: 'mock-test', title: { fa: 'آزمون شبیه‌سازی', en: 'Mock Test' }, icon: '📋' },
      { id: 'final-review', title: { fa: 'مرور نهایی', en: 'Final Review' }, icon: '✅' },
    ],
  },
  {
    id: 'ausbildung',
    icon: '🔧',
    title: { fa: 'آوسبیلدونگ', en: 'Ausbildung' },
    description: {
      fa: 'آمادگی برای دوره‌های فنی و حرفه‌ای',
      en: 'Prepare for vocational training programs',
    },
    color: 'from-teal-400 to-cyan-600',
    totalStages: 8,
    stages: [
      { id: 'basics', title: { fa: 'اصطلاحات فنی پایه', en: 'Basic Technical Terms' }, icon: '🔤' },
      { id: 'tools', title: { fa: 'ابزار و تجهیزات', en: 'Tools & Equipment' }, icon: '🔨' },
      { id: 'safety', title: { fa: 'ایمنی در کار', en: 'Workplace Safety' }, icon: '🦺' },
      { id: 'colleagues', title: { fa: 'ارتباط با همکاران', en: 'Colleague Communication' }, icon: '👥' },
      { id: 'instructions', title: { fa: 'دستورالعمل‌ها', en: 'Instructions' }, icon: '📋' },
      { id: 'reports', title: { fa: 'گزارش‌نویسی', en: 'Report Writing' }, icon: '📄' },
      { id: 'customers', title: { fa: 'ارتباط با مشتری', en: 'Customer Contact' }, icon: '🤝' },
      { id: 'exam-prep', title: { fa: 'آمادگی آزمون نهایی', en: 'Final Exam Prep' }, icon: '🎯' },
    ],
  },
];

export default JOURNEYS;